#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path('../../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'pry'
require 'rack'
require 'anycable'
require 'litecable'
require './app'

# Turn AnyCable compatibility mode
LiteCable.anycable!

Anycable.connection_factory = App::Connection

Anycable::Server.start
