#!/usr/bin/env ruby
# frozen_string_literal: true
require_relative './boot.rb'

# Turn AnyCable compatibility mode
LiteCable.anycable!

Anycable.connection_factory = Websocket::Connection

Anycable::Server.start
