#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
Bundler.require(:default)
require 'active_support/inflector'

Dir['*/**/**.rb'].each { |file| require_relative file }

Ohm.redis = Redic.new('redis://127.0.0.1:6379')

binding.pry
